spring.application.name=kiksi1

# Server Port (Using 9090 so it doesn't clash with anything else)
server.port=9090

# XAMPP MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/kiksi_db
spring.datasource.username=root
spring.datasource.password=

# Tell Spring to automatically create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
